---
version: '2'
services: 
  ecommerce-db:
    hostname: ecommerce-db
    container_name: ecommerce-db
    build:
      context: ../postgres
      dockerfile: ecommerce.Dockerfile
    ports:
      - "5432:5432"
    networks:
      - docker-databases
  analytics-db:
    hostname: analytics-db
    container_name: analytics-db
    build:
      context: ../postgres
      dockerfile: analytics.Dockerfile
    ports: 
      - "5433:5432"
    networks:
      - docker-databases
networks:
  docker-databases:
    name: docker-database-network